- project:
    name: 'openstack-bifrost-verify'
#--------------------------------
# branches
#--------------------------------
    stream:
        - master:
            branch: '{stream}'
#--------------------------------
# projects
#--------------------------------
    project:
        - 'openstack':
            project-repo: 'https://git.openstack.org/openstack/bifrost'
            clone-location: '/opt/bifrost'
        - 'opnfv':
            project-repo: 'https://gerrit.opnfv.org/gerrit/releng'
            clone-location: '/opt/releng'
#--------------------------------
# distros
#--------------------------------
    distro:
        - 'trusty':
            disabled: false
            dib-os-release: 'trusty'
            dib-os-element: 'ubuntu-minimal'
            dib-os-packages: 'openssh-server,vlan,vim,less,bridge-utils,language-pack-en,iputils-ping,rsyslog,curl'
        - 'centos7':
            disabled: false
            dib-os-release: '7'
            dib-os-element: 'centos7'
            dib-os-packages: 'openssh-server,vim,less,bridge-utils,iputils,rsyslog,curl'
        - 'suse':
            disabled: true
            dib-os-release: 'suse'
            dib-os-element: 'suse'
            dib-os-packages: ''
#--------------------------------
# type
#--------------------------------
    type:
        - virtual
#--------------------------------
# jobs
#--------------------------------
    jobs:
        - '{project}-bifrost-verify-{distro}-{type}-{stream}'
#--------------------------------
# job templates
#--------------------------------
- job-template:
    name: '{project}-bifrost-verify-{distro}-{type}-{stream}'

    disabled: '{obj:disabled}'

    concurrent: false

    properties:
        - build-blocker:
            use-build-blocker: true
            blocking-jobs:
                - '.*-bifrost-verify.*-{type}'
            block-level: 'NODE'

    parameters:
        - string:
            name: PROJECT
            default: '{project}'
        - string:
            name: PROJECT_REPO
            default: '{project-repo}'
        - string:
            name: CLONE_LOCATION
            default: '{clone-location}'
        - string:
            name: DISTRO
            default: '{distro}'
        - string:
            name: DIB_OS_RELEASE
            default: '{dib-os-release}'
        - string:
            name: DIB_OS_ELEMENT
            default: '{dib-os-element}'
        - string:
            name: DIB_OS_PACKAGES
            default: '{dib-os-packages}'
        - string:
            name: CLEAN_DIB_IMAGES
            default: 'true'
        - label:
            name: SLAVE_LABEL
            default: 'infra-{type}-{distro}'

    scm:
        - git:
            url: '$PROJECT_REPO'
            refspec: '$GERRIT_REFSPEC'
            branches:
                - 'origin/$GERRIT_BRANCH'
            skip-tag: true
            choosing-strategy: 'gerrit'
            timeout: 10
            wipe-workspace: true

    triggers:
        - '{project}-gerrit-trigger':
            branch: '{branch}'

    builders:
        - description-setter:
            description: "Built on $NODE_NAME"
        - shell:
            !include-raw-escape: ./bifrost-verify.sh

    publishers:
        - email:
            recipients: fatih.degirmenci@ericsson.com yroblamo@redhat.com mchandras@suse.de jack.morgan@intel.com zhang.jun3g@zte.com.cn
#--------------------------------
# trigger macros
#--------------------------------
- trigger:
    name: 'openstack-gerrit-trigger'
    triggers:
        - gerrit:
            server-name: 'review.openstack.org'
            escape-quotes: true
            trigger-on:
                - patchset-created-event:
                    exclude-drafts: 'false'
                    exclude-trivial-rebase: 'false'
                    exclude-no-code-change: 'false'
                - comment-added-contains-event:
                    comment-contains-value: 'recheck'
            custom-url: '* $JOB_NAME $BUILD_URL'
            silent-start: true
            projects:
              - project-compare-type: 'PLAIN'
                project-pattern: 'openstack/bifrost'
                branches:
                  - branch-compare-type: 'ANT'
                    branch-pattern: '**/{branch}'
                forbidden-file-paths:
                  - compare-type: ANT
                    pattern: 'doc/**'
                  - compare-type: ANT
                    pattern: 'releasenotes/**'
            readable-message: true
- trigger:
    name: 'opnfv-gerrit-trigger'
    triggers:
        - gerrit:
            server-name: 'gerrit.opnfv.org'
            trigger-on:
                - patchset-created-event:
                    exclude-drafts: 'false'
                    exclude-trivial-rebase: 'false'
                    exclude-no-code-change: 'false'
                - draft-published-event
                - comment-added-contains-event:
                    comment-contains-value: 'recheck'
                - comment-added-contains-event:
                    comment-contains-value: 'reverify'
            projects:
              - project-compare-type: 'ANT'
                project-pattern: 'releng'
                branches:
                  - branch-compare-type: 'ANT'
                    branch-pattern: '**/{branch}'
                file-paths:
                  - compare-type: ANT
                    pattern: 'prototypes/bifrost/**'
                  - compare-type: ANT
                    pattern: 'jjb/infra/**'
            readable-message: true
