---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: b05e028c5881819161d11cb543fd96a30c06cceb # frozen: v1.32.0
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: fc260393cc4ec09f8fc0a5ba4437f481c8b55dc1 # frozen: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/rhysd/actionlint
    rev: 7b75d16d41920ec126e6f3269db0c6f3ab613c38 # frozen: v1.6.25
    hooks:
      - id: actionlint
