---
- hosts: jumphost
  become: true
  vars_files:
    - "vars/pods.yaml"
    - "vars/defaults.yaml"
  tasks:
    ##
    # install osa
    ##
    - name: remove openstack-ansible directories
      file:
        path: "{{ osa_path }}"
        state: absent
    - name: remove openstack-ansible config directories
      file:
        path: "{{ osa_etc_path }}"
        state: absent
    - name: "clone openstack-ansible {{osa_branch}}"
      git:
        repo: "{{ osa_url }}"
        dest: "{{ osa_path }}"
        version: "{{ osa_branch }}"
    # - name: set ansible-role-requirements
    #   copy:
    #     dest: "{{ osa_path }}/ansible-role-requirements.yml"
    #     src: files/ansible-role-requirements.yml
