##############################################################################
# Copyright (c) 2018 Linux Foundation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
$schema: 'http://json-schema.org/schema#'
$id: 'https://github.com/opnfv/releng/blob/master/releases/schema.yaml'

additionalProperties: false

properties:
  team:
    type: 'string'
  release-model:
    type: 'string'
    enum:
      - 'stable'
      - 'non-release'
  type:
    type: 'string'
    enum:
      - 'installer'
      - 'testing'
      - 'feature'
      - 'tools'
  upstream:
    type: 'string'
  repos:
    type: 'array'
    items:
      type: 'object'
      additionalProperties: false
      properties:
        name:
          type: 'string'
        releases:
          type: 'array'
          items:
            type: 'object'
            additionalProperties: false
            properties:
              version:
                type: 'string'
              hash:
                type: 'string'
              required: ['version', 'hash']
  branches:
    type: 'array'
    items:
      type: 'object'
      additionalProperties: false
      properties:
        repo:
          type: 'string'
        name:
          type: 'string'
        location:
          type: 'string'
      required: ['name', 'repo', 'location']
  release-notes:
    type: 'string'
  required: ['branches', 'type', 'team']
