#!/bin/bash
set -e
set -o pipefail

export PATH=$PATH:/usr/local/bin/

git_sha1="$(git rev-parse HEAD)"
res_build_date=$(date -u +"%Y-%m-%d_%H-%M-%S")

# Result directory in the docker file 
# to be used only with CI
dir_result="/home/opnfv/functest/results"

# Clean the results directory
# remove json file for rally, export only html
# json should have been pushed into the DB
if [ -e f $dir_result/rally/*.json]; then
    rm $dir_result/rally/*.json
fi

# Several information are required: date and testbed
# date is generated by functest so on the artifact, the results shall be under functest/<testbed id>/date/
testbed=$NODE_NAME

project_artifact=functest/$testbed/$res_build_date

# copy folder to artifact
if [ -d "$dir_result" ]; then
    if [ "$(ls -A $dir_result)" ]; then
          echo "copy result files to artifact $project_artifact"
          gsutil cp -r "$dir_result" gs://artifacts.opnfv.org/"$project_artifact"/
          
          # delete local results
          # should not be useful as the container is about to die...just in case
          rm -Rf /home/opnfv/functest/results/*
    else
          echo "Result folder is empty"
    fi
else
    echo "No result folder found"
fi
